ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude_types: [svg]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
