title: Atomistic Scale Simulations
author: Antonia Statt
copyright: "2025"
only_build_toc_files: true

exclude_patterns: [.github/*]

execute:
  execute_notebooks: force

html:
  baseurl: https://stattlab.github.io/atomistic-scale-simulations
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - replacements
    - smartquotes

repository:
  url: https://github.com/stattlab/atomistic-scale-simulations
  branch: main

bibtex_bibfiles:
    - references/references.bib

sphinx:
  extensions:
    - myst_nb
  extra_extensions:
    - sphinx_image_inverter
  local_extensions:
    example_admonition: _extensions
    solution_dropdown: _extensions
    learning_outcome_admonition: _extensions
    exercise_admonition: _extensions
  config:
    bibtex_reference_style: super
    bibtex_default_style: plain
    inverter_saturation: 1.5

    mathjax3_config:
      tex:
        macros:
          "d": ["{\\operatorname{d}\\!{#1}}", 1]
          "dd": ["{\\d{}^{#1} #2 \\over \\d{#3}^{#1}}", 3]
          "pp": ["{\\partial^{#1} #2 \\over \\partial #3^{#1}}", 3]
          "td": ["{\\left(\\pp{#1}{#2}{#3} \\right)_{#4}}", 4]
          "ubar": ["\\underline{#1}", 1]
          "vv": ["\\mathbf{#1}", 1]
