name: deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout book
        uses: actions/checkout@v5

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build book
        run: |
          jupyter-book build -W -n --keep-going .

      - name: Disable Jekyll to serve static HTML
        run: |
          touch _build/html/.nojekyll

      - name: Deploy book to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: preview
          folder: "_build/html"
          force: false
